/**
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Astro
 */
class Astro extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.sunrise = this.constructor.getValue(obj.sunrise);
        this.sunset = this.constructor.getValue(obj.sunset);
        this.moonrise = this.constructor.getValue(obj.moonrise);
        this.moonset = this.constructor.getValue(obj.moonset);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'sunrise', realName: 'sunrise' },
            { name: 'sunset', realName: 'sunset' },
            { name: 'moonrise', realName: 'moonrise' },
            { name: 'moonset', realName: 'moonset' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Astro;
