/**
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Forecastday1
 */
class Forecastday1 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.date = this.constructor.getValue(obj.date);
        this.dateEpoch = this.constructor.getValue(obj.dateEpoch || obj.date_epoch);
        this.day = this.constructor.getValue(obj.day);
        this.astro = this.constructor.getValue(obj.astro);
        this.hour = this.constructor.getValue(obj.hour);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'date', realName: 'date' },
            { name: 'dateEpoch', realName: 'date_epoch' },
            { name: 'day', realName: 'day', type: 'Day' },
            { name: 'astro', realName: 'astro', type: 'Astro' },
            { name: 'hour', realName: 'hour', array: true, type: 'Hour' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Forecastday1;
