/**
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TimezoneJsonResponse
 */
class TimezoneJsonResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.region = this.constructor.getValue(obj.region);
        this.country = this.constructor.getValue(obj.country);
        this.lat = this.constructor.getValue(obj.lat);
        this.lon = this.constructor.getValue(obj.lon);
        this.tzId = this.constructor.getValue(obj.tzId || obj.tz_id);
        this.localtimeEpoch = this.constructor.getValue(obj.localtimeEpoch || obj.localtime_epoch);
        this.localtime = this.constructor.getValue(obj.localtime);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'region', realName: 'region' },
            { name: 'country', realName: 'country' },
            { name: 'lat', realName: 'lat' },
            { name: 'lon', realName: 'lon' },
            { name: 'tzId', realName: 'tz_id' },
            { name: 'localtimeEpoch', realName: 'localtime_epoch' },
            { name: 'localtime', realName: 'localtime' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TimezoneJsonResponse;
