/**
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CurrentJsonResponse = require('../lib/Models/CurrentJsonResponse');
const Location = require('../lib/Models/Location');
const Current = require('../lib/Models/Current');
const Condition = require('../lib/Models/Condition');
const ForecastJsonResponse = require('../lib/Models/ForecastJsonResponse');
const Forecast = require('../lib/Models/Forecast');
const Forecastday = require('../lib/Models/Forecastday');
const Day = require('../lib/Models/Day');
const Astro = require('../lib/Models/Astro');
const HistoryJsonResponse = require('../lib/Models/HistoryJsonResponse');
const Forecast1 = require('../lib/Models/Forecast1');
const Forecastday1 = require('../lib/Models/Forecastday1');
const Hour = require('../lib/Models/Hour');
const SearchJsonResponse = require('../lib/Models/SearchJsonResponse');
const IpJsonResponse = require('../lib/Models/IpJsonResponse');
const TimezoneJsonResponse = require('../lib/Models/TimezoneJsonResponse');
const AstronomyJsonResponse = require('../lib/Models/AstronomyJsonResponse');
const Astronomy = require('../lib/Models/Astronomy');

const classMap = {
    CurrentJsonResponse,
    Location,
    Current,
    Condition,
    ForecastJsonResponse,
    Forecast,
    Forecastday,
    Day,
    Astro,
    HistoryJsonResponse,
    Forecast1,
    Forecastday1,
    Hour,
    SearchJsonResponse,
    IpJsonResponse,
    TimezoneJsonResponse,
    AstronomyJsonResponse,
    Astronomy,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
